In [2]:
import numpy as np
A=np.array([[1,2,3],[3,4,6]])
B=np.array([[5,6,7],[7,8,9]])
print(np.concatenate((A,B,B),axis=1))
print(A+B)
print(B)
C=A[:,0]>2
C=C.astype(np.int64)
print((C))

[[1 2 3 5 6 7 5 6 7]
 [3 4 6 7 8 9 7 8 9]]
[[ 6  8 10]
 [10 12 15]]
[[5 6 7]
 [7 8 9]]
[0 1]


In [10]:
C=np.c_[A,B]
D=np.zeros(len(C))
print(D)

[0. 0.]


In [12]:
print(np.random.randint(0,3,3))

[2 2 1]


In [1]:
import numpy as np
a = np.array([True, False])
print(a)
print(a + 0)

[ True False]
[1 0]


In [14]:
print(np.zeros(17))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [2]:
A=[0,0,0,0]
A[1]=1
print(A)

[0, 1, 0, 0]
