In [1]:
#cat test_gpu.py
import torch
 
if __name__ == '__main__':
    #测试 CUDA
    print("Support CUDA ?: ", torch.cuda.is_available())
    x = torch.tensor([10.0])
    x = x.cuda()
    print(x)
 
    y = torch.randn(2, 3)
    y = y.cuda()
    print(y)
 
    z = x + y
    print(z)
 
   # 测试 CUDNN
    from torch.backends import cudnn
    print("Support cudnn ?: ",cudnn.is_acceptable(x))

Support CUDA ?:  True
tensor([10.], device='cuda:0')
tensor([[ 0.6967,  0.1682, -0.8440],
        [-0.6793,  0.4362, -1.0806]], device='cuda:0')
tensor([[10.6967, 10.1682,  9.1560],
        [ 9.3207, 10.4362,  8.9194]], device='cuda:0')
Support cudnn ?:  True


In [ ]:
import torch
print(torch.eye(2,2))
print(torch.zeros(2,3))
print(torch.linspace(1,10,4))
print(torch.rand(2,3))
print(torch.randn(2,3))
print(torch.zeros_like(torch.rand(2,3)))

In [9]:
import random
#r = random.sample(set([1, 2, 3, 4, 5, 6]), 1)[0]
r = random.randint(0, 255)
print(r)

89


In [13]:
a=[12,'+',10,'*',2]
print(eval(''.join([str(i) for i in a])))

32
